name: TagExample
version: '${project.version}'
main: me.kap.gfw.tagexample.TagExample
api-version: '1.20'

commands:
  start:
    description: 'starts the game'
  end:
    description: 'ends the game'
  setLocation:
    description: 'sets a location'